export const reservation = {
SPACE : ' ',
ISBN_NUMBER : 'ISBN Number',
AUTHOR_NAME : 'Author Name',
RELEASE_YEAR : 'Book Release Year',
ISSUE_DATE : 'Book Issue Date',
RETURN_DATE : 'Book Return Date',
DIVIDER : ':',
RETURN_BOOK : 'Return Book',
NO_BOOKS : 'No Books Reserved',
RESERVE_BOOK : 'Reserve Book',
MY_RESERVATIONS : 'My Reservations',
SEARCH_MESSAGE : 'If you do not know ISBN number you can search in home page.',
SEARCH : 'Search',
RESERVE_BOOK_Title : 'Reserve this Book',
};
